Stabilization to prepare for broader distribution.

diff --git a/lib/describe b/lib/describe
--- a/lib/describe
+++ b/lib/describe
@@ -1,19 +1,28 @@
 export APIGEE_INSTANCE_JSON=$(curl -H "$AUTH" -s "https://apigee.googleapis.com/v1/organizations/$PROJECT_ID/instances" | jq -r ".instances[0]")
+if [[ -z "$APIGEE_INSTANCE_JSON" || "$APIGEE_INSTANCE_JSON" = null ]]; then
+    printf "${ERROR_COLOR}Project ${HIGHLIGHT_COLOR}${PROJECT_ID}${ERROR_COLOR} does not have an Apigee instance.\n${NO_COLOR}"
+    exit 1
+fi
 export APIGEE_INSTANCE_NAME=$(echo $APIGEE_INSTANCE_JSON | jq -r ".name")
 export APIGEE_INSTANCE_HOST_IP=$(echo $APIGEE_INSTANCE_JSON | jq -r ".host")
+export APIGEE_INSTANCE_LOCATION=$(echo $APIGEE_INSTANCE_JSON | jq -r ".location")
+export TARGET_SERVICE=$(echo $APIGEE_INSTANCE_JSON | jq -r '.instances[0].serviceAttachment')
 export APIGEE_HOST_NAME=$(curl -H "$AUTH" -s "https://apigee.googleapis.com/v1/organizations/${PROJECT_ID}/envgroups" | jq -r ".environmentGroups[0].hostnames[0]")
 
-echo "**************************************"
-echo "*****     APIGEE ORG DETAILS     *****"
-echo "**************************************"
-printf "host name: ${HIGHLIGHT_COLOR}${APIGEE_HOST_NAME}${NO_COLOR}\n"
-printf "instance ip: ${HIGHLIGHT_COLOR}${APIGEE_INSTANCE_HOST_IP}${NO_COLOR}\n"
-printf "instance name: ${APIGEE_INSTANCE_NAME}\n"
-echo "**************************************"
+printf "${INFO_COLOR}"
+printf "*******************************************\n"
+printf "*****     APIGEE INSTANCE DETAILS     *****\n"
+printf "*******************************************\n"
+printf "org: ${HIGHLIGHT_COLOR}${PROJECT_ID}${INFO_COLOR}\n"
+printf "host name: ${HIGHLIGHT_COLOR}${APIGEE_HOST_NAME}${INFO_COLOR}\n"
+printf "instance ip: ${HIGHLIGHT_COLOR}${APIGEE_INSTANCE_HOST_IP}${INFO_COLOR}\n"
+printf "location: ${HIGHLIGHT_COLOR}${APIGEE_INSTANCE_LOCATION}${INFO_COLOR}\n"
+printf "*******************************************\n"
+printf "${NO_COLOR}"
 
 if [[ -z "$SUPPRESS_DESCRIBE" || "$SUPPRESS_DESCRIBE" = false ]]; then
     echo
-    echo "Try the following from a machine instance inside the ${NETWORK_NAME} network of project ${PROJECT_ID}..."
+    echo "Try the following from a machine instance inside project ${PROJECT_ID}..."
     echo
     printf "${EXAMPLE_COLOR}curl -k -H \"Host: ${APIGEE_HOST_NAME}\" \"https://${APIGEE_INSTANCE_HOST_IP}/hello-world\"\n"
     printf "${NO_COLOR}\n"
diff --git a/lib/provision b/lib/provision
--- a/lib/provision
+++ b/lib/provision
@@ -1,23 +1,38 @@
-set -e
-
 gcloud services enable apigee.googleapis.com \
   servicenetworking.googleapis.com compute.googleapis.com \
   cloudkms.googleapis.com --project=$PROJECT_ID
 
-export RANGE_NAME=google-svcs
+export CONFIRM=$(gcloud alpha apigee organizations list --filter="name:${PROJECT_ID}" --format="value(name)")
+if [[ -z "${CONFIRM}" ]]; then
+  echo "Confirmed no Apigee organization exists for project ${PROJECT_ID}."
+else
+  printf "${WARN_COLOR}Apigee organization already exists for project ${PROJECT_ID}."
+  exit
+fi
 
+export DEFAULT_LOCATION=$(gcloud config list compute/region --format=json | jq -r '.compute.region')
+if [[ -z "${DEFAULT_LOCATION}" ]]; then
+  printf "${ERROR_COLOR}Missing --location argument.${NO_COLOR}\n"
+  exit 1
+fi
+
+if [[ -z "${NETWORK_NAME}" ]]; then
+  printf "${ERROR_COLOR}Missing --network argument.${NO_COLOR}\n"
+  exit 1
+fi
 export CONFIRM=$(gcloud compute networks list --project=$PROJECT_ID --format="value(name)" --filter="name:${NETWORK_NAME}")
 if [[ -z "${CONFIRM}" ]]; then
   echo "Provisioning a network."
-  gcloud compute networks create demonet --project=$PROJECT_ID
+  gcloud compute networks create ${NETWORK_NAME} --project=$PROJECT_ID
 else
   echo "Network previously provisioned."
 fi
 
-export CONFIRM=$(gcloud compute addresses list --project=$PROJECT_ID --format="value(name)" --filter="name:${RANGE_NAME}")
+export APIGEE_PEERING_RANGE=apigee-peering
+export CONFIRM=$(gcloud compute addresses list --project=$PROJECT_ID --format="value(name)" --filter="name=${APIGEE_PEERING_RANGE}")
 if [[ -z "${CONFIRM}" ]]; then
   echo "Provisioning a peering address range without specifying addresses. Use --addresses instead to specify."
-  gcloud compute addresses create $RANGE_NAME \
+  gcloud compute addresses create $APIGEE_PEERING_RANGE \
     --global \
     --prefix-length=21 \
     --description="Peering range for Apigee services" \
@@ -47,19 +62,15 @@ if [[ -z "${CONFIRM}" ]]; then
   gcloud services vpc-peerings connect \
     --service=servicenetworking.googleapis.com \
     --network=$NETWORK_NAME \
-    --ranges=$RANGE_NAME,google-managed-services-support-1 \
+    --ranges=$APIGEE_PEERING_RANGE,google-managed-services-support-1 \
     --project=$PROJECT_ID
 else
   echo "VPC peering previously established."
 fi
 
-export CONFIRM=$(gcloud alpha apigee organizations list --filter="name:${PROJECT_ID}" --format="value(name)")
-if [[ -z "${CONFIRM}" ]]; then
-  gcloud alpha apigee organizations provision \
-    --runtime-location=$RUNTIME_LOCATION \
-    --analytics-region=$ANALYTICS_REGION \
-    --authorized-network=$NETWORK_NAME \
-    --project=$PROJECT_ID
-else
-  echo "Apigee organization previously provisioned."
-fi
+echo "Creating a Apigee organization ${PROJECT_ID}..."
+gcloud alpha apigee organizations provision \
+  --runtime-location=$DEFAULT_LOCATION \
+  --analytics-region=$DEFAULT_LOCATION \
+  --authorized-network=$NETWORK_NAME \
+  --project=$PROJECT_ID
diff --git a/lib/setup-external-access b/lib/setup-external-access
--- a/lib/setup-external-access
+++ b/lib/setup-external-access
@@ -1,15 +1,27 @@
+if [[ -z "${NETWORK_NAME}" ]]; then
+  printf "${ERROR_COLOR}Missing --network argument.${NO_COLOR}\n"
+  exit 1
+fi
+
+printf "Setting up ${HIGHLIGHT_COLOR}external${NO_COLOR} access...\n\n"
+
+echo "Checking details of the Apigee instance for project ${PROJECT_ID}..."
+echo
+export SUPPRESS_DESCRIBE=true # Minimize console output. Mainly just set env vars.
+. $REPO_DIRECTORY/lib/describe # Query the Apigee API and set details to env vars.
+echo
+
 DEFAULT_RESOURCE_NAME=apigee
-TARGET_SERVICE=$(curl -X GET -H "$AUTH" -s "https://apigee.googleapis.com/v1/organizations/$PROJECT_ID/instances" | jq -r '.instances[0].serviceAttachment')
 
 TEMP_CHECK=$(gcloud compute network-endpoint-groups list --project=$PROJECT_ID --format="value(NAME)" --filter="name:${DEFAULT_RESOURCE_NAME}")
 if [[ -z "${TEMP_CHECK}" ]]; then
   echo "Provisioning NEG for PSC Target Service ${TARGET_SERVICE}." 
-  gcloud compute network-endpoint-groups create apigee \
+  gcloud compute network-endpoint-groups create $DEFAULT_RESOURCE_NAME \
     --network-endpoint-type=private-service-connect \
     --psc-target-service=$TARGET_SERVICE \
     --network=$NETWORK_NAME \
     --subnet=$NETWORK_NAME \
-    --region=$RUNTIME_LOCATION \
+    --region=$APIGEE_INSTANCE_LOCATION \
     --project=$PROJECT_ID
 else
   echo "Network endpoint group (NEG) previously provisioned."
@@ -24,6 +36,9 @@ if [[ -z "${TEMP_CHECK}" ]]; then
 else
   echo "External IP address previously reserved for load balancer."
 fi
+APIGEE_LB_IP=$(gcloud compute addresses list --filter="name=$DEFAULT_RESOURCE_NAME" \
+    --global --project=$PROJECT_ID --format="value(address)")
+printf "${INFO_COLOR}Load balancer IP address: ${HIGHLIGHT_COLOR}${APIGEE_LB_IP}${NO_COLOR}\n"
 
 TEMP_CHECK=$(gcloud compute backend-services list \
   --filter="name:${DEFAULT_RESOURCE_NAME}" --format="value(name)")
@@ -41,7 +56,7 @@ if [[ -z "${TEMP_CHECK}" ]]; then
   {
     gcloud compute backend-services add-backend $DEFAULT_RESOURCE_NAME \
       --network-endpoint-group=$DEFAULT_RESOURCE_NAME \
-      --network-endpoint-group-region=$RUNTIME_LOCATION \
+      --network-endpoint-group-region=$APIGEE_INSTANCE_LOCATION \
       --global --project=$PROJECT_ID
   } || {
     # Ensure that the next time we run this script, we try again to add
@@ -64,7 +79,24 @@ else
   echo "Load balancer frontend previously created."
 fi
 
-APIGEE_HOST_NAME=34.160.112.252.nip.io
+if [[ -z "${NEW_APIGEE_HOST_NAME}" ]]; then
+  printf "${WARN_COLOR}No ${HIGHLIGHT_COLOR}--domain${WARN_COLOR} argument. Using what is already configured for the Apigee instance: ${HIGHLIGHT_COLOR}${APIGEE_HOST_NAME}${NO_COLOR}\n"
+else
+  NEW_APIGEE_HOST_NAME=$(echo "$NEW_APIGEE_HOST_NAME" | sed -e "s/{IP-ADDRESS}/${APIGEE_LB_IP}/g")
+  if [[ "${NEW_APIGEE_HOST_NAME}" = "${APIGEE_HOST_NAME}" ]]; then
+    echo "Specified domain name matches existing Apigee environment group configuration. No change."
+  else
+    echo "Changing domain name configuration for Apigee instance from ${APIGEE_HOST_NAME} to ${NEW_APIGEE_HOST_NAME}..."
+    curl -s "https://apigee.googleapis.com/v1/organizations/$PROJECT_ID/envgroups/eval-group" \
+      -H "$AUTH" \
+      -X PATCH \
+      -H "Content-Type:application/json" \
+      -d '{
+        "hostnames":["'${APIGEE_HOST_NAME}'"]
+      }' > /dev/null
+    APIGEE_HOST_NAME=$NEW_APIGEE_HOST_NAME
+  fi
+fi
 
 TEMP_CHECK=$(gcloud compute ssl-certificates list \
   --filter="name:${DEFAULT_RESOURCE_NAME}" --format="value(MANAGED_STATUS)")
@@ -80,15 +112,7 @@ else
   echo "SSL certificate previously provisioned."
 fi
 
-# TODO: Optimize by checking prior configuration before changing.
-echo "Making sure domain name is property set on Apigee environment group..."
-curl -s "https://apigee.googleapis.com/v1/organizations/$PROJECT_ID/envgroups/eval-group" \
-  -H "$AUTH" \
-  -X PATCH \
-  -H "Content-Type:application/json" \
-  -d '{
-    "hostnames":["'${APIGEE_HOST_NAME}'"]
-  }' > /dev/null
+
 
 TEMP_CHECK=$(gcloud compute target-https-proxies list \
   --filter="name=${DEFAULT_RESOURCE_NAME}" --format="value(name)")
@@ -120,7 +144,7 @@ echo "Attempting to invoke an API being managed by the Apigee instance..."
 TEMP_CMD="curl -s https://${APIGEE_HOST_NAME}/hello-world"
 printf "\n${EXAMPLE_COLOR}${TEMP_CMD}${NO_COLOR}\n\n"
 API_RESPONSE=$($TEMP_CMD)
-printf "API response: ${HIGHLIGHT_COLOR}${API_RESPONSE}${NO_COLOR}\n"
+printf "${INFO_COLOR}API response: ${HIGHLIGHT_COLOR}${API_RESPONSE}${NO_COLOR}\n"
 
 #gcloud compute target-http-proxies create ${DEFAULT_RESOURCE_NAME}-http --url-map=$DEFAULT_RESOURCE_NAME
 #gcloud compute forwarding-rules create http-content-rule \
diff --git a/lib/test-internal-access b/lib/test-internal-access
--- a/lib/test-internal-access
+++ b/lib/test-internal-access
@@ -1,27 +1,27 @@
+if [[ -z "${NETWORK_NAME}" ]]; then
+  printf "${ERROR_COLOR}Missing --network argument.${NO_COLOR}\n"
+  exit 1
+fi
+
 printf "Testing ${HIGHLIGHT_COLOR}internal${NO_COLOR} access...\n"
 
-SSH_RULE_NAME=default-allow-ssh
+SSH_RULE_NAME=${NETWORK_NAME}-allow-ssh
 TEMP_CHECK=$(gcloud compute firewall-rules list \
-    --filter="name:${SSH_RULE_NAME} AND network:${NETWORK_NAME}" \
-    --format="value(name)")
+    --filter="name:${SSH_RULE_NAME}" \
+    --format="value(name)" --project=${PROJECT_ID})
 if [[ -z "${TEMP_CHECK}" ]]; then
     gcloud compute firewall-rules create ${SSH_RULE_NAME} --project=${PROJECT_ID} \
-        --network=projects/${PROJECT_ID}/global/networks/${NETWORK_NAME} \
+        --network=${NETWORK_NAME} \
         --description="Allows TCP connections from any source to any instance on the network using port 22." \
         --direction=INGRESS --priority=65534 \
         --source-ranges=0.0.0.0/0 --action=ALLOW --rules=tcp:22
-else
-    echo "Firewall rule to allow SSH already established."
 fi
 
-echo "Querying the Apigee instance for project ${PROJECT_ID} for details..."
-echo
 export SUPPRESS_DESCRIBE=true # Minimize console output. Mainly just set env vars.
 . $REPO_DIRECTORY/lib/describe # Query the Apigee API and set details to env vars.
 echo
 
 TEMP_INSTANCE=temp-demo-apigee-client-instance
-echo "Checking to see if temp instance '$TEMP_INSTANCE' has already been created."
 TEMP_CHECK=$(gcloud compute instances list --project=${PROJECT_ID} --filter="name:$TEMP_INSTANCE" --format="value(status)")
 if [[ -z "${TEMP_CHECK}" ]]; then
     echo "Creating temporary instance inside the VPC as a test client..."
@@ -34,23 +34,27 @@ if [[ -z "${TEMP_CHECK}" ]]; then
     # The instance will show RUNNING status immediately after the above
     # command returns complete, but it still takes some time before an
     # attempt to connect via SSH is successful.   
+    echo "Giving some time for the new compute instance to become available for SSH..."
     sleep 30 # Total hack, for now.
+elif [[ "${TEMP_CHECK}" = "RUNNING" ]]; then
+    echo "Test client compute instance FOUND with status RUNNING."
 else
-    echo "Instance found. Status: $TEMP_CHECK"
+    printf "${ERROR_COLOR}Test client compuete instance has an unexpected status: ${HIGHLIGHT_COLOR}${TEMP_CHECK}${NO_COLOR}\n"
+    exit 1
 fi
 
 {
-    echo "Running the following command from the temporary instance inside the VPC."
-    printf "\n${EXAMPLE_COLOR}curl -k -H \"Host: ${APIGEE_HOST_NAME}\" \"https://${APIGEE_INSTANCE_HOST_IP}/hello-world\"\n\n${NO_COLOR}"
+    printf "\n${INFO_COLOR}Running the following command from the temporary instance inside the VPC.${NO_COLOR}\n"
+    printf "\n${EXAMPLE_COLOR}curl -k -H \"Host: ${APIGEE_HOST_NAME}\" \"https://${APIGEE_INSTANCE_HOST_IP}/hello-world\"\n${NO_COLOR}"
 
     # Run a command on the instance to invoke an API in Apigee.
     API_RESPONSE=$(gcloud compute ssh ${TEMP_INSTANCE} --project=${PROJECT_ID} \
         --zone=us-central1-a --tunnel-through-iap --strict-host-key-checking=no \
-        --command="curl -k -H \"Host: ${APIGEE_HOST_NAME}\" -s \"https://${APIGEE_INSTANCE_HOST_IP}/hello-world\"")
+        --command="curl -k -H \"Host: ${APIGEE_HOST_NAME}\" -s \"https://${APIGEE_INSTANCE_HOST_IP}/hello-world\"" 2> /dev/null)
     # Show API response.
-    printf "\nAPI response as the output of above curl command: ${HIGHLIGHT_COLOR}${API_RESPONSE}${NO_COLOR}\n"
+    printf "\n${INFO_COLOR}API response as the output of above curl command: ${HIGHLIGHT_COLOR}${API_RESPONSE}${NO_COLOR}\n"
     if [ "$API_RESPONSE" = "Hello, Guest!" ]; then
-        printf "Test result: ${HIGHLIGHT_COLOR}success${NO_COLOR}\n"
+        printf "${INFO_COLOR}Test result: ${HIGHLIGHT_COLOR}success${NO_COLOR}\n\n"
     else
         printf "Test result: ${ERROR_COLOR}failure${NO_COLOR}\n"
     fi
@@ -63,4 +67,9 @@ fi
 }
 
 # Delete the temporary instance.
-gcloud compute instances delete ${TEMP_INSTANCE} --project=${PROJECT_ID} --quiet
+if [[ $* == *--keep-instance ]]; then
+    echo "Keeping temporary client instance for quick re-execution."
+else 
+    echo "Cleaning up..."
+    gcloud compute instances delete ${TEMP_INSTANCE} --project=${PROJECT_ID} --quiet
+fi
